import type { Metadata } from 'next';
import { Noto_Sans } from 'next/font/google';
import './globals.css';

const notoSans = Noto_Sans({
	subsets: ['latin'],
	weight: ['300', '400', '500', '600', '700'],
	preload: true,
	variable: '--font-noto',
});

export const metadata: Metadata = {
	title: 'Layout meta',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={notoSans.className}>{children}</body>
		</html>
	);
}
